### ISSUE TITLE
argument order matters in inlines, but not in blocks

### ISSUE THREAD

**Issue by BrianHicks** [mdgriffith/elm-markup#15]
What the title says! This was surprising to me when I wrote my first inline. In this case, I was converting from Markdown:

```markdown
[say hey](mailto:test@example.com)
```

which became

```
{Link|say hey|url=mailto:test@example.com}
```

Buuuuuut that didn't work because of the argument order, like this:

```elm
link : Inline InlineContent
link =
    Mark.inline "Link"
        (\url title ->
            Link
                { url = url
                , title = List.map textToRich title
                }
        )
        |> Mark.inlineString "url"
        |> Mark.inlineText
```

(p.s. I was also a little confused why this library has the `thing2`, `thing3`, etc pattern for blocks, but the inline `json-decode-pipeline` style for inlines. Why the difference?)

**Comment by mdgriffith** [comment]
This was changed in`v3` so that order doesn't matter in either place!  Thanks :)
