### ISSUE TITLE
creating a inline code snippet is awkward

### ISSUE THREAD

**Issue by BrianHicks** [mdgriffith/elm-markup#16]
In Markdown, you can do this:

```markdown
Look at the code in `examples/BlogPost.elm`
```

> Look at the code in `examples/BlogPost.elm`

But because of the slash, this is awkward in elm-markup. `inlineText` will interpret any formatting characters according to plain text rules, so you have to use a named argument in the inline instead.

**Comment by mdgriffith** [comment]
You're right!

Now there is a `verbatim` inline concept which I think fits this quite nicely:https://package.elm-lang.org/packages/mdgriffith/elm-markup/3.0.0/Mark#verbatim
