### ISSUE TITLE
newlines in paragraphs are parsed as new paragraphs

### ISSUE THREAD

**Issue by BrianHicks** [mdgriffith/elm-markup#17]
when writing prose in a markup language, I put each sentence on a new line. This lets me refactor my writing easily: just move lines to move sentences around. Nice benefit of being able to see that I'm properly varying sentence length as well.

elm-markup will parse this style as new paragraphs each time. So the following gets rendered as four paragraphs, not two:

```
If you're a first time conference speaker, you still have a really good shot of getting in.
Our community gets stronger the more new and diverse voices there are, so we want to hear from you!
In fact, we are reserving several slots for first-time speakers.

If you are comfortable being identified as a new speaker for the purposes of the call for speakers, please indicate that in the `First time speaker` field on {Link|url=https://cfp.elm-conf.us/events/elm-conf-2018|your proposal}.
```

This also comes up with hard line wrapping: I've seen a lot of documentation which wraps at 80 characters in source code. If we wanted to, say, parse Elm documentation in this way to embed interactive examples, we'd have to remove non-consecutive newlines before parsing.

**Comment by mdgriffith** [comment]
Good call!  in `v3`, single newlines are allowed for styled text.

Love the examples.
