### ISSUE TITLE
Out of sync?

### ISSUE THREAD

**Issue by jxxcarlson** [mdgriffith/elm-markup#19]
Am getting the errors below using ` elm make src/Main.elm --output=editor.js`:

```
I cannot find a `Mark.Error` type:

67|     , errors : List Mark.Error
                        ^^^^^^^^^^
The `Mark` module does not expose a `Error` type. ...
 .```

Fixed this, then

```
 $ elm make src/Main.elm --output=editor.js
Detected errors in 1 module.
-- NAMING ERROR --------------------------------------------------- src/Main.elm

I cannot find a `Mark.Edit.Error` type:

387|     -> Result (List Mark.Edit.Error) ( Cursor, Mark.Parsed )
                         ^^^^^^^^^^^^^^^
The `Mark.Edit` module does not expose a `Error` type. ..
```

**Comment by mdgriffith** [comment]
Thanks!  I updated the example with the correct types.
