### ISSUE TITLE
Nesting blocks

### ISSUE THREAD

**Issue by lzrski** [mdgriffith/elm-markup#2]
Hi! Thanks for the Elm Markup. It rocks!

I'm working on a slideshow program with custom, interactive _widgets_ nested in the slides. The Elm Markup seems like a perfect building block for that.

Is it possible to nest one block inside another, like a `counter` inside a `slide` section` in this example: https://ellie-app.com/3TxSxQn8zLna1 ? Or is there another way?

**Comment by mdgriffith** [comment]
Hello!  This is addressed in `v2`, which I just released :)

In `v2` you can parse a document to any data structure, as well as nest blocks within each other!
