### ISSUE TITLE
Compiler doesn't allow --debug and opaque types  && Failure to update document

### ISSUE THREAD

**Issue by tgelu** [mdgriffith/elm-markup#21]
I am trying to edit a ``Mark.Parsed``

**First try**
https://ellie-app.com/5GhRZRzHxD3a1
In one instance, if I define a ``Msg`` that holds a ``Mark.Edit.Id`` the code fails to compile with some internal error with the ``--debug`` flag.

```
elm: Map.!: given key is not an element in the map
CallStack (from HasCallStack):
 error, called at ./Data/Map/Internal.hs:610:17 in containers-0.5.11.0-K2TDqgYtGUcKxAY1UqVZ3R:Data.Map.Internal
```
Without the ``--debug`` flag the updating fails with ``I tried to edit your document but couldn't find any blocks with the Mark.Edit.Id that you provided``

**Second Try**
https://ellie-app.com/5Gj5wNd3cMCa1 - click the text and see the ``Logs`` tab
If I define the ``Msg`` to hold a ``String`` instead of a ``Mark.Edit.Id`` and convert to and from it, I still get the same update fail where the id is not found, as above.

**Comment by tgelu** [comment]
I believe at least one mistake of mine was that I was applying a style edit on something that was not a styled text block. I managed to apply the edit after a few more tries.
If that is true then the error message could be a bit more truthful. It was not the ID that was wrong but the type of block.

**Comment by mdgriffith** [comment]
Good call on having a better error message here.  I've implemented some more editing error messages beyond Id Not Found: https://github.com/mdgriffith/elm-markup/commit/b7a9aaddaa33d99f1f83378f58f1f09ab99fd848

A patch release should be out soon.  I'm going to close this issue, but thanks a lot for reporting it!
