### ISSUE TITLE
Mark.record behaves strangely when fields have commas

### ISSUE THREAD

**Issue by MattCheely** [mdgriffith/elm-markup#23]
`Mark.record` will fail to parse blocks when there's a comma in the field content, unless it's the last field, in which case it parses up to the comma, and anything after that is treated as the rest of the document.

https://ellie-app.com/5HzMQsXmcnxa1

**Comment by mdgriffith** [comment]
Thanks!  Found the issue.  Hopefully will have a release in the next few days.
