### ISSUE TITLE
Custom element on last (or second to last) line breaks the parser

### ISSUE THREAD

**Issue by lzrski** [mdgriffith/elm-markup#3]
See https://ellie-app.com/3XXCryvVrzba1

It works if you add a blank line at the end of the markup. So the workaround is easy in the example, but gets tricky when the content is in separate file. Many text editors have a feature of removing trailing empty lines. That's how I've run into it.

**Comment by mdgriffith** [comment]
I believe this is fixed in `v2` because blocks are no longer closed by 2 newlines, but by a change in indentation.
