### ISSUE TITLE
Lamdera issues caused by flattened module exposing structure

### ISSUE THREAD

**Issue by Evelios** [mdgriffith/elm-markup#45]
From the lamdera compiler is giving me the following error `The 'Document' type from mdgriffith/elm-markup:Mark.Internal.Description is referenced, but I can't find it!`because this is `a type which has been intentionally hidden by the author, so it cannot be used!`. I'm assuming this is because this is the lamdera compiler trying to drill down into document types to provide proper encoding/decoding for these types.

**Full compiler log**
```
I ran into the following problems when checking Lamdera core types:

FrontendMsg:

- The `Document` type from mdgriffith/elm-markup:Mark.Internal.Description is referenced,
  but I can't find it! You can try `lamdera install mdgriffith/elm-markup`, otherwise this might 
  be a type which has been intentionally hidden by the author, so it cannot be used!

See <https://dashboard.lamdera.app/docs/wire> for more info.

Alpha warning: also, a number of types outside Types.elm are referenced, see
`lamdera check` for more info.
```

This was a consequence of your choice to break apart your work into `Internal` files which are then exposed by an alias into the top file to flatten the project.

**src/Mark.elm**
```elm
import Mark.Internal.Description as Desc exposing (..)

type alias Document data =
    Desc.Document data
```

Having said all this, I don't know if this should directly fall into your lap since this isn't an elm specific problem and more of a lamdera issue. I'm going to just fork your project for now to get around this issue. Even if this isn't something you feel obligated to address, I think it is important to understand the consequences of design and file management choices on the larger ecosystem.

**Comment by mdgriffith** [comment]
This is a pretty common pattern in elm packages and hiding implementation details is a central idea of modularity, so not sure what I can do to address this without exposing a bunch of internals that people shouldn't mess with 🤔 

Is there anyway to give lamdera a manual set of encoders/decoders?

**Comment by mdgriffith** [comment]
I spoke with Mario on the Lamdera channel on slack and he's exploring some solutions for this sort of thing longer term.   His intention is that Lamdera doesn't impose additional restrictions on the Elm ecosystem.

So, the current way forward is to vendor the package(clone it locally) like you're doing.
